# Generated by Django 5.0.6 on 2024-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='available_cars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
