# Generated by Django 5.0.6 on 2024-07-09 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventory', '0002_carcategory_available_cars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='bought_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
